language: python

python: 
  -3.6.3

sudo: enabled

env:
  - DJANGO_VERSION=2.0.6 

 before_install:
 — sudo apt-get -qq update
 — sudo apt-get -y install python3-pip
 — sudo apt-get install python-virtualenv
 
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

script:
  - python3 ./manage.py test
