language: python

python:
  -"3.6.3"

sudo: enabled

env:
  - DJANGO_VERSION=2.0.6 

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

script:
  - python3 ./manage.py test
